import Head from 'next/head'
import { Grid, Button as ButtonMUI } from '@mui/material'
import { useState } from 'react'
import Button from '@/components/Button'
import Icon from '@/components/Icon'
import ModalWrapper from '@/components/ModalWrapper'
import ModalNew from '@/components/ModalNew'

const initialState = {
  scheduleUsers: [],
  scheduleUnitsById: {},
  selectedProfessionals: [],
  selectedProfessionalsById: {},
  scheduleUnits: null,
  selectedUser: null,
  selectedUnit: null,
  scheduleModal: false,
  unitModal: false,
  deleteModal: false,
  isCreatingSchedules: false,
  isLoading: true,
}

const initialStateModal = {
  openModal: ``,
}

export default function Home() {
  const [state, setState] = useState(initialState)
  const [modalConfig, setModalConfig] = useState(initialStateModal)
  return (
    <>
      <Head>
        <title>Workshop - MUI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container minHeight="100vh" justifyContent="center" alignItems="center">
        {/* REEMPLAZAR ESTE MODAL Y BOTON UTILIZANDO COMPONENTES DE MATERIAL UI
        ⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇*/}

        {/* <ModalWrapper
          {...state}
          {...modalConfig}
          onClose={() => setModalConfig({openModal: ``})}
        /> */}
        <ModalNew />

        {/* ⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆ */}
      </Grid>
    </>
  )
}
