import * as React from 'react';
import Head from 'next/head'
import { Grid } from '@mui/material'
import { useState } from 'react'
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import Modal from '@mui/material/Modal';
import NewScheduleUnit from '@/components/NewScheduleUnit';


const initialState = {
  scheduleUsers: [],
  scheduleUnitsById: {},
  selectedProfessionals: [],
  selectedProfessionalsById: {},
  scheduleUnits: null,
  selectedUser: null,
  selectedUnit: null,
  scheduleModal: false,
  unitModal: false,
  deleteModal: false,
  isCreatingSchedules: false,
  isLoading: true,
}

const initialStateModal = {
  open: false,
}

const style = {
  position: 'absolute' as 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  width: "70vw",
  bgcolor: 'background.paper',
  boxShadow: 24,
  p: 4,
};

function BasicModal({open, onClose}: {open: boolean, onClose: () => void}) {
  return (
    <div>
      
      <Modal
        open={open}
        onClose={onClose}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description"
      >
        <Box sx={style}>
        <NewScheduleUnit onClose={onClose} />
        </Box>
      </Modal>
    </div>
  );
}

export default function Home() {
  const [state, setState] = useState(initialState)
  const [modalConfig, setModalConfig] = useState(initialStateModal)

  return (
    <>
      <Head>
        <title>Workshop - MUI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container minHeight='100vh' justifyContent='center' alignItems='center'>
        <Button onClick={() => setModalConfig({ open: true })}>Agredar unidad agenda</Button>
        <BasicModal 
          {...state}
          {...modalConfig} 
          onClose={() => setModalConfig({ open: false })}
          />
        
      </Grid>
    </>
  )
}
